name: alsun-webrtc-demo
namespace: alsunai
version: 0.0.1
author: Alsun AI Team
display_name: Alsun AI WebRTC Client
tags:
  - demo
  - community
homepage: https://github.com/abdurrhmaan/alsun-webrtc-plugin