name: alsun-webrtc-plugin
namespace: alsun
version: 0.0.1
author: Alsun AI Team
display_name: Alsun AI WebRTC client
tags:
  - demo
  - alsun
homepage: https://github.com/abdurrhmaan/alsun-webrtc-plugin
